/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-10-02 09:01:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598233866429L));
    _jspx_dependants.put("jar:file:/D:/workspace/2020_7_yncho/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hanacard-spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>하나카드</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  \r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Muli:300,400,700,900\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/fonts/icomoon/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/owl.carousel.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/jquery.fancybox.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/aos.css\">\r\n");
      out.write("  <link href=\"/hanacard-spring-mvc/resources/css/jquery.mb.YTPlayer.min.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/style.css\">\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href =\"/hanacard-spring-mvc/resources/images/favicon16.png\">\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/fonts.css\">\r\n");
      out.write("    \r\n");
      out.write("  <!-- <style>\r\n");
      out.write("  \tbody { font-family: 'Times New Roman', Times, Arial, Helvetica, sans-serif; }\r\n");
      out.write("  </style> -->\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\" data-offset=\"300\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-wrap\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"site-mobile-menu site-navbar-target\">\r\n");
      out.write("      <div class=\"site-mobile-menu-header\">\r\n");
      out.write("        <div class=\"site-mobile-menu-close mt-3\">\r\n");
      out.write("          <span class=\"icon-close2 js-menu-toggle\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"site-mobile-menu-body\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"py-2 bg-light\">\r\n");
      out.write("    <!-- <div class=\"py-2 bg-light\" style = \"font-family: HanaUL; font-size: 20px;\"> -->\r\n");
      out.write("    <!-- <div class=\"py-2 bg-light\"> -->\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("          <div class=\"col-lg-9 d-none d-lg-block\">\r\n");
      out.write("            <!-- <a href=\"#\" class=\"small mr-3\"><span class=\"icon-question-circle-o mr-2\"></span> Have a questions?</a> \r\n");
      out.write("            <a href=\"#\" class=\"small mr-3\"><span class=\"icon-phone2 mr-2\"></span> 10 20 123 456</a> \r\n");
      out.write("            <a href=\"#\" class=\"small mr-3\"><span class=\"icon-envelope-o mr-2\"></span> info@mydomain.com</a>  -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3 text-right\">\r\n");
      out.write("          \r\n");
      out.write("          \t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <header class=\"site-navbar py-4 js-sticky-header site-navbar-target\" role=\"banner\">\r\n");
      out.write("    <!-- <header class=\"site-navbar py-4 js-sticky-header site-navbar-target\" role=\"banner\" style = \"font-family: HanaL; font-size: 22px;\"> -->\r\n");
      out.write("    <!-- <header class=\"site-navbar py-4 js-sticky-header site-navbar-target\" role=\"banner\"> -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"d-flex align-items-center\">\r\n");
      out.write("          <div class=\"site-logo\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"d-block\">\r\n");
      out.write("              <img src=\"/hanacard-spring-mvc/resources/images/hanacard_logo_down.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"mr-auto\">\r\n");
      out.write("            <nav class=\"site-navigation position-relative text-right\" role=\"navigation\">\r\n");
      out.write("              <ul class=\"site-menu main-menu js-clone-nav mr-auto d-none d-lg-block\">\r\n");
      out.write("                <li class=\"has-children\">\r\n");
      out.write("                <!-- <li class=\"active\"> -->\r\n");
      out.write("                  <a href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage\" class=\"nav-link text-left\">마이페이지</a>\r\n");
      out.write("                  <ul class=\"dropdown\">\r\n");
      out.write("                  <!-- <ul class=\"dropdown\" style = \"font-family: HanaL; font-size: 50px;\"> -->\r\n");
      out.write("                  <!-- <ul class=\"dropdown\"> -->\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage\">종합 대시보드</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/owncard\">보유카드정보</a></li>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"has-children\">\r\n");
      out.write("                  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mychart\" class=\"nav-link text-left\">나만의차트</a>\r\n");
      out.write("                  <ul class=\"dropdown\">\r\n");
      out.write("                    <!-- <li><a href=\"teachers.html\">카드타입별순위</a></li> -->\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mychart/totalRank\">통합순위</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mychart/discountRank\">할인순위</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mychart/pointRank\">적립순위</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mychart/mileRank\">마일리지순위</a></li>\r\n");
      out.write("                    <!-- <li><a href=\"about.html\">전월실적별순위</a></li> -->\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"has-children\">\r\n");
      out.write("                  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart\" class=\"nav-link text-left\">하나차트</a>\r\n");
      out.write("                  <!-- <a href=\"about.html\" class=\"nav-link text-left\">나만의 차트</a> -->\r\n");
      out.write("                  <ul class=\"dropdown\">\r\n");
      out.write("                    <!-- <li><a href=\"teachers.html\">카드타입별순위</a></li> -->\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart/benefitRank\">인기혜택별순위</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart/ageRank\">연령대별순위</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart/annualfeeRank\">연회비별순위</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart/typeRank\">카드타입별순위</a></li>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <!-- <li><a href=\"about.html\">전월실적별순위</a></li> -->\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("                <!-- <li class=\"has-children\"> -->\r\n");
      out.write("                  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\" class=\"nav-link text-left\">검색/비교</a>\r\n");
      out.write("                  <!-- <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"teachers.html\">조건별검색</a></li>\r\n");
      out.write("                    <li><a href=\"about.html\">키워드검색</a></li>\r\n");
      out.write("                    <li><a href=\"about.html\">개인화추천</a></li>\r\n");
      out.write("                  </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <!-- <li>\r\n");
      out.write("                  <a href=\"admissions.html\" class=\"nav-link text-left\">검색/비교</a>\r\n");
      out.write("                </li> -->\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board\" class=\"nav-link text-left\">고객센터</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- <li>\r\n");
      out.write("                    <a href=\"contact.html\" class=\"nav-link text-left\">Contact</a>\r\n");
      out.write("                  </li> -->\r\n");
      out.write("              </ul>                                                                                                                                                                                                                                                                                          </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("            <div class=\"social-wrap\">\r\n");
      out.write("              <a href=\"https://www.facebook.com/hanacard\"><span class=\"icon-facebook\"></span></a>\r\n");
      out.write("              <!-- <a href=\"#\"><span class=\"icon-twitter\"></span></a>\r\n");
      out.write("              <a href=\"#\"><span class=\"icon-linkedin\"></span></a> -->\r\n");
      out.write("              <a href=\"https://www.instagram.com/global_must_have/\"><span class=\"icon-instagram\"></span></a>\r\n");
      out.write("              <a href=\"https://www.youtube.com/channel/UCsnlgvmpylLeDhxPQvUcMCA\"><span class=\"icon-youtube\"></span></a>\r\n");
      out.write("\r\n");
      out.write("              <a href=\"#\" class=\"d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black\"><span\r\n");
      out.write("                class=\"icon-menu h3\"></span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"hero-slide owl-carousel site-blocks-cover\">\r\n");
      out.write("      <div class=\"intro-section\" style=\"background-image: url('/hanacard-spring-mvc/resources/images/hero_1.jpg');\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-12 mx-auto text-center\" data-aos=\"fade-up\">\r\n");
      out.write("              <!-- <h1>Smart Life를 선도하는 Smart 금융 </h1> -->\r\n");
      out.write("              <h1>Smart Life</h1>\r\n");
      out.write("              <h1>Smart Finance</h1>\r\n");
      out.write("              <!-- <h3>Smart Life를 선도하는 Smart 금융 </h3> -->\r\n");
      out.write("              <!-- <h5>INNOVATOR by KEB Hana Card</h5> -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"intro-section\" style=\"background-image: url('/hanacard-spring-mvc/resources/images/hero_1.jpg');\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-12 mx-auto text-center\" data-aos=\"fade-up\">\r\n");
      out.write("              <h1>INNOVATOR by</h1>\r\n");
      out.write("              <h1>Hana Card</h1>\r\n");
      out.write("            \r\n");
      out.write("              <!-- <h1>고객님과 함께 하나카드의 새로운 도전을 시작합니다.</h1> -->\r\n");
      out.write("              <!-- <h1>INNOVATOR by KEB Hana Card</h1> -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- <div class=\"site-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5 justify-content-center text-center\">\r\n");
      out.write("          <div class=\"col-lg-4 mb-5\">\r\n");
      out.write("            <h2 class=\"section-title-underline mb-5\">\r\n");
      out.write("              <span>전체 BEST 3 CARD</span>\r\n");
      out.write("              <span>Why Academics Works</span>\r\n");
      out.write("            </h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 mb-4 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"feature-1 border\">\r\n");
      out.write("              <div class=\"icon-wrapper bg-primary\">\r\n");
      out.write("                <span class=\"flaticon-mortarboard text-white\"></span>\r\n");
      out.write("                <span style =\"color: white; font-size: 40px;\">1</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"feature-1-content\">\r\n");
      out.write("                <h2>Personalize Learning</h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit morbi hendrerit elit</p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary px-4 rounded-0\">Learn More</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 mb-4 mb-lg-0\">\r\n");
      out.write("            <div class=\"feature-1 border\">\r\n");
      out.write("              <div class=\"icon-wrapper bg-primary\">\r\n");
      out.write("                <span class=\"flaticon-school-material text-white\"></span>\r\n");
      out.write("                <span style =\"color: white; font-size: 40px;\">2</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"feature-1-content\">\r\n");
      out.write("                <h2>Trusted Courses</h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit morbi hendrerit elit</p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary px-4 rounded-0\">Learn More</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div> \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 mb-4 mb-lg-0\">\r\n");
      out.write("            <div class=\"feature-1 border\">\r\n");
      out.write("              <div class=\"icon-wrapper bg-primary\">\r\n");
      out.write("                <span class=\"flaticon-library text-white\"></span>\r\n");
      out.write("                <span style =\"color: white; font-size: 40px;\">3</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"feature-1-content\">\r\n");
      out.write("                <h2>Tools for Students</h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit morbi hendrerit elit</p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-primary px-4 rounded-0\">Learn More</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div> \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"site-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-5 justify-content-center text-center\">\r\n");
      out.write("          <div class=\"col-lg-6 mb-5\">\r\n");
      out.write("            <h1 class=\"section-title-underline mb-3\">\r\n");
      out.write("              <span style =\"font-weight: bold;\">혜택별 BEST CARD</span>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <p>이번 달 혜택별 BEST CARD를 살펴보세요!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12\">\r\n");
      out.write("              <div class=\"owl-slide-3 owl-carousel\">\r\n");
      out.write("                  <div class=\"course-1-item\">\r\n");
      out.write("                    <figure class=\"thumnail\">\r\n");
      out.write("                      <a href=\"course-single.html\"><img src=\"/hanacard-spring-mvc/resources/images/Any PLUS 카드.png\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("                      <!-- <div class=\"price\">연 ￦5,000</div> -->\r\n");
      out.write("                      <div class=\"category\"><h3>SMART ANY(스마트 애니)카드</h3></div>  \r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"course-1-content pb-4\">\r\n");
      out.write("                      <h2>생활 혜택 BEST</h2>\r\n");
      out.write("                      <div class=\"rating text-center mb-3\">\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <p class=\"desc mb-4\">모든 가맹점 0.8% 청구할인</p>\r\n");
      out.write("                      <p><a href=\"course-single.html\" class=\"btn btn-primary rounded-0 px-4\">카드 보러가기</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("      \r\n");
      out.write("                  <div class=\"course-1-item\">\r\n");
      out.write("                    <figure class=\"thumnail\">\r\n");
      out.write("                      <a href=\"course-single.html\"><img src=\"/hanacard-spring-mvc/resources/images/모두의 쇼핑.png\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("                      <!-- <div class=\"price\">$99.00</div> -->\r\n");
      out.write("                      <div class=\"category\"><h3>모두의 쇼핑</h3></div>  \r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"course-1-content pb-4\">\r\n");
      out.write("                      <h2>마트/쇼핑 혜택 BEST</h2>\r\n");
      out.write("                      <div class=\"rating text-center mb-3\">\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <p class=\"desc mb-4\">모바일 전용 카드로 즐기는 쇼핑 혜택!</p>\r\n");
      out.write("                      <p><a href=\"course-single.html\" class=\"btn btn-primary rounded-0 px-4\">카드 보러가기</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("      \r\n");
      out.write("                  <div class=\"course-1-item\">\r\n");
      out.write("                    <figure class=\"thumnail\">\r\n");
      out.write("                      <a href=\"course-single.html\"><img src=\"/hanacard-spring-mvc/resources/images/CLUB SK(클럽 SK)카드.png\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("                      <!-- <div class=\"price\">$99.00</div> -->\r\n");
      out.write("                      <div class=\"category\"><h3>CLUB SK(클럽 SK)카드</h3></div>  \r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"course-1-content pb-4\">\r\n");
      out.write("                      <h2>통신/교통 혜택 BEST</h2>\r\n");
      out.write("                      <div class=\"rating text-center mb-3\">\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <p class=\"desc mb-4\">100만 고객이 선택한 SK의 모든 혜택</p>\r\n");
      out.write("                      <p><a href=\"courses-single.html\" class=\"btn btn-primary rounded-0 px-4\">카드 보러가기</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"course-1-item\">\r\n");
      out.write("                    <figure class=\"thumnail\">\r\n");
      out.write("                        <a href=\"course-single.html\"><img src=\"/hanacard-spring-mvc/resources/images/My Trip 1Q Global VIVA.png\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("                      <!-- <div class=\"price\">$99.00</div> -->\r\n");
      out.write("                      <div class=\"category\"><h3>My Trip 1Q Global VIVA</h3></div>  \r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"course-1-content pb-4\">\r\n");
      out.write("                      <h2>레저/여행/항공 BEST</h2>\r\n");
      out.write("                      <div class=\"rating text-center mb-3\">\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <p class=\"desc mb-4\">해외여행을 위한 MUST HAVE 카드</p>\r\n");
      out.write("                      <p><a href=\"course-single.html\" class=\"btn btn-primary rounded-0 px-4\">카드 보러가기</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("      \r\n");
      out.write("                  <!-- <div class=\"course-1-item\">\r\n");
      out.write("                    <figure class=\"thumnail\">\r\n");
      out.write("                        <a href=\"course-single.html\"><img src=\"/hanacard-spring-mvc/resources/images/course_5.jpg\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("                      <div class=\"price\">$99.00</div>\r\n");
      out.write("                      <div class=\"category\"><h3>Web Design</h3></div>  \r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"course-1-content pb-4\">\r\n");
      out.write("                      <h2>How To Create Mobile Apps Using Ionic</h2>\r\n");
      out.write("                      <div class=\"rating text-center mb-3\">\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <p class=\"desc mb-4\">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique accusantium ipsam.</p>\r\n");
      out.write("                      <p><a href=\"course-single.html\" class=\"btn btn-primary rounded-0 px-4\">Enroll In This Course</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("      \r\n");
      out.write("                  <div class=\"course-1-item\">\r\n");
      out.write("                    <figure class=\"thumnail\">\r\n");
      out.write("                        <a href=\"course-single.html\"><img src=\"/hanacard-spring-mvc/resources/images/course_6.jpg\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("                      <div class=\"price\">$99.00</div>\r\n");
      out.write("                      <div class=\"category\"><h3>Mobile Application</h3></div>  \r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"course-1-content pb-4\">\r\n");
      out.write("                      <h2>How To Create Mobile Apps Using Ionic</h2>\r\n");
      out.write("                      <div class=\"rating text-center mb-3\">\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                        <span class=\"icon-star2 text-warning\"></span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <p class=\"desc mb-4\">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique accusantium ipsam.</p>\r\n");
      out.write("                      <p><a href=\"course-single.html\" class=\"btn btn-primary rounded-0 px-4\">Enroll In This Course</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div> -->\r\n");
      out.write("      \r\n");
      out.write("              </div>\r\n");
      out.write("      \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t  <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<!-- WEB-INF 폴더는 보안이라, 프론트에서는 접근할 수 없다 -->\r\n");
      out.write("\t\t<!-- 다만 백엔드에서는 접근 가능하다. (jsp 등) -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- .site-wrap -->\r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#51be78\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery.fancybox.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery.sticky.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/jquery.mb.YTPlayer.min.js\"></script>\r\n");
      out.write("  <script src=\"/hanacard-spring-mvc/resources/js/main.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          \t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("          \t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("          \t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /index.jsp(64,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginVO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t            <a href = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\" class=\"small mr-3\"><span class=\"icon-unlock-alt\"></span> 로그인</a>\r\n");
          out.write("\t\t            <a href=\"register.html\" class=\"small btn btn-primary px-4 py-2 rounded-0\"><span class=\"icon-users\"></span> 회원가입</a>\r\n");
          out.write("          \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          \t\t\t<span class=\"small mr-3\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("\t\t            <a href = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\" class=\"small mr-3\"><span class=\"icon-unlock-alt\"></span> 로그아웃</a>\r\n");
          out.write("          \t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
