/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-10-02 13:03:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.chart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class benefitRank_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getInstance();
  _jspx_fnmap_1.mapFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
  _jspx_fnmap_1.mapFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598233866429L));
    _jspx_dependants.put("jar:file:/D:/workspace/2020_7_yncho/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hanacard-spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace/2020_7_yncho/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hanacard-spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>하나카드</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Muli:300,400,700,900\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/fonts/icomoon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/jquery.fancybox.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/aos.css\">\r\n");
      out.write("<link href=\"/hanacard-spring-mvc/resources/css/jquery.mb.YTPlayer.min.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/style.css\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href =\"/hanacard-spring-mvc/resources/images/favicon16.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hanacard-spring-mvc/resources/css/fonts.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t.modal-backdrop {\r\n");
      out.write("\t   background-color: rgb(0,0,0,0.1);\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/hanacard-spring-mvc/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* $('#start').click(function(){\r\n");
      out.write("\t\t\talert('hello');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}) */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#searchBtn').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetTopThree();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* $('#lifeA').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert('life');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#mart_shoppingA').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert('mart_shoppingA');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#comm_transA').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert('comm_transA');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#leisure_travle_flightA').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert('leisure_travle_flightA');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}) */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getTopThree() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlet category = $('#category').text();\r\n");
      out.write("\t\tif(category == '생활')\r\n");
      out.write("\t\t\tcategory = 'life';\r\n");
      out.write("\t\tif(category == '마트/쇼핑')\r\n");
      out.write("\t\t\tcategory = 'mart_shopping';\r\n");
      out.write("\t\tif(category == '통신/교통')\r\n");
      out.write("\t\t\tcategory = 'comm_trans';\r\n");
      out.write("\t\tif(category == '레저/여행/항공')\r\n");
      out.write("\t\t\tcategory = 'leisure_travle_flight';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t//alert('ajax category ==> ' + category)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t//let year = $('#start').val().substring(2,4);\r\n");
      out.write("\t\t//let month = $('#start').val().substring(5, 7);\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlet year = $('#bottomYear').val().substring(0,4);\r\n");
      out.write("\t\tlet month = $('#bottomMonth').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(month == '전체'){\r\n");
      out.write("\t\t\tmonth = 'all';\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\tmonth = $('#bottomMonth').val().slice(0,-1); //끝문자부터 자르기\r\n");
      out.write("\t\t\tif(month.length == 1)\r\n");
      out.write("\t\t\t\tmonth = '0' + month;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t//url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/recocard/' + year + '/' + month,\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart/benefitrank/' + category + '/' + year + '/' + month,\r\n");
      out.write("\t\t\ttype : 'get', \r\n");
      out.write("\t\t\t//async : false,\r\n");
      out.write("\t\t\tsuccess : function(data) { // data의 type : string --> json으로 바꾸자  ::  이용~ \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert('차트 alert 성공');\r\n");
      out.write("\t\t\t\t//alert('data: ' + data);\r\n");
      out.write("\t\t\t\tlet list = JSON.parse(data);\r\n");
      out.write("\t\t\t\t//alert('list: ' + list);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t        $(\"#ulList\").empty();\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        \r\n");
      out.write("\t           var addListHtml =\"\";\r\n");
      out.write("\t             $(list).each(function(index){\r\n");
      out.write("\t            \t \r\n");
      out.write("\t            \t //alert('this.cardName.substring(0,1) ===> ' + this.cardName.substring(0,1) );\r\n");
      out.write("\t            \t \r\n");
      out.write("\t            \t addListHtml += \"<li>\";\r\n");
      out.write("\t            \t addListHtml += \"<div style = \\\"background-color: #E8F5FF; box-shadow: 20px 20px 20px grey;\\\">\";\r\n");
      out.write("\t            \t addListHtml += \"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\";\r\n");
      out.write("\t            \t addListHtml += \"<span style = \\\"vertical-align: middle; font-weight : bold; font-size: 100px; color: black;\\\">\" + (index+1) + \"</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\";\r\n");
      out.write("\t            \t addListHtml += \"<span>\";\r\n");
      out.write("\t            \t \r\n");
      out.write("\t            \t \r\n");
      out.write("\t            \t if(this.cardName.substring(0,1) == '#'){\r\n");
      out.write("\t            \t\t \r\n");
      out.write("\t\t            \t addListHtml += \"<img src=\\\"/hanacard-spring-mvc/resources/images/\" + this.cardName.substring(1, this.cardName.length)  + \".png\\\" style = \\\"width : 132px; height : 84px;\\\">\";\r\n");
      out.write("\r\n");
      out.write("\t            \t } else{\r\n");
      out.write("\t            \t\t \r\n");
      out.write("\t\t            \t addListHtml += \"<img src=\\\"/hanacard-spring-mvc/resources/images/\" + this.cardName + \".png\\\" style = \\\"width : 132px; height : 84px;\\\">\";\r\n");
      out.write("\r\n");
      out.write("\t            \t }\r\n");
      out.write("\t            \t \r\n");
      out.write("\t            \t addListHtml += \"</span>\";\r\n");
      out.write("\t            \t addListHtml += \"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\";\r\n");
      out.write("\t            \t addListHtml += \"<span style =\\\"font-size: 30px; vertical-align: sub; color: black;\\\">\" + this.cardName + \"</span>\";\r\n");
      out.write("\t            \t addListHtml += \"</div>\";\r\n");
      out.write("\t            \t addListHtml += \"</li>\";\r\n");
      out.write("\t            \t addListHtml += \"<br>\";\r\n");
      out.write("\t            \t \r\n");
      out.write("\t            \t /* addListHtml += this.cardName.substring(0,1);\r\n");
      out.write("\t            \t addListHtml += this.cardName;\r\n");
      out.write("\t            \t addListHtml += this.count; */\r\n");
      out.write("\t            \t \r\n");
      out.write("\t             })\r\n");
      out.write("\t             \r\n");
      out.write("\t\t        $('#ulList').append(addListHtml); // 또는 반복문 끝나고 append\r\n");
      out.write("\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        //이 이후에 다시 ul태그 내에 forEach 돌면서 li태그 추가해야 함.\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\talert('차트 ajax 실패')\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doChangeCondition(obj){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//alert('함수호출이 가능합니다.');\r\n");
      out.write("\t\t//alert('obj => ' + obj);\r\n");
      out.write("\t\t//$('#category').text();\r\n");
      out.write("\t\t$('#category').text(obj);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetTopThree();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\" data-offset=\"300\">\r\n");
      out.write("\t<!-- .site-wrap starts -->\r\n");
      out.write("\t<div class=\"site-wrap\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topMenue.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<div class=\"site-section ftco-subscribe-1 site-blocks-cover pb-4\" style=\"background-image: url('/hanacard-spring-mvc/resources/images/bg_1.jpg')\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row align-items-end justify-content-center text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-7\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"mb-0\">하나차트</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>혜택별로 손님들이 선호하는 카드를 살펴보세요.</p>\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<div class=\"custom-breadcrumns border-bottom\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a href=\"index.html\">Home</a> <span class=\"mx-3 icon-keyboard_arrow_right\"></span> \r\n");
      out.write("\t\t\t\t<span>하나차트</span> <span class=\"mx-3 icon-keyboard_arrow_right\"></span> \r\n");
      out.write("\t\t\t\t<span class=\"current\">인기혜택별순위</span>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<!-- Begin Page Content -->\r\n");
      out.write("\t\t<div class=\"container\" align=\"center\">\r\n");
      out.write("\t\t<!-- <div class=\"container\"> -->\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<!-- <div style = \"display: table-cell; vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"m-0 font-weight-bold text-primary\" style=\"display:inline;\">마트/쇼핑 혜택 TOP3</h1>\r\n");
      out.write("\t\t\t\t\t이 문서내에 id가 exampleMoal인 것을 참조\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\">조건 변경</button>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<h1 id = \"category\" class=\"m-0 font-weight-bold text-primary\" style=\"display:inline; vertical-align: sub;\">생활</h1>\r\n");
      out.write("\t\t\t\t<h1 class=\"m-0 font-weight-bold text-primary\" style=\"display:inline; vertical-align: sub;\"> 혜택 TOP3</h1>\r\n");
      out.write("\t\t\t\t<button style = \"vertical-align: super;\" type=\"button\" class=\"btn btn-primary btn-sm\" data-toggle=\"modal\" data-target=\"#exampleModal\">조건 변경</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style = \"vertical-align: high;\">\r\n");
      out.write("\t\t\t\t<!-- <div style = \"margin-bottom: auto;\"> -->\r\n");
      out.write("\t\t\t\t\t<!-- 이 문서내에 id가 exampleMoal인 것을 참조 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <select class=\"form-control form-control-lg\">\r\n");
      out.write("\t\t\t\t\t<option>Large select</option>\r\n");
      out.write("\t\t\t\t</select> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <div align=\"center\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<select style = \"width: 200px;\" class=\"form-control form-control-md\"> lg, md, sm\r\n");
      out.write("\t\t\t\t\t\t<option>2020년 9월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2020년 8월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2020년 7월</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <input type=\"month\"> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <div>\r\n");
      out.write("\t\t\t\t\t<input type=\"month\" id=\"start\" name=\"start\" min=\"2018-01\" value=\"2020-10\" style =\"font-size: 20px;\">\r\n");
      out.write("\t\t\t\t\t<button id = \"searchBtn\">조회</button>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"d-sm-flex align-items-center justify-content-end mb-4 mt-5\">\r\n");
      out.write("\t\t\t\t\t<!-- Example single danger button -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<select class=\"selectpicker\" data-style=\"btn-success\" id=\"bottomYear\" style =\"font-family: sans-serif;\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <select class=\"selectpicker\" multiple data-max-options=\"2\"> -->\r\n");
      out.write("\t\t\t\t\t\t<option>2020년</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2019년</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2018년</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<select class=\"selectpicker\" data-style=\"btn-success\" id=\"bottomMonth\" style =\"font-family: sans-serif;\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <select class=\"selectpicker\" multiple data-max-options=\"2\"> -->\r\n");
      out.write("\t\t\t\t\t\t<option>전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option>1월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>3월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>4월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>5월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>6월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>7월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>8월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>9월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>10월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>11월</option>\r\n");
      out.write("\t\t\t\t\t\t<option>12월</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<button class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\" id=\"searchBtn\">\r\n");
      out.write("\t\t\t\t\t<!-- <button class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\" onclick=\"getBottomSpecific()\"> -->\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-download fa-sm text-white-50\"></i> 조회\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<!-- <a href=\"#\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\"><i class=\"fas fa-download fa-sm text-white-50\"></i> 조회</a> -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <input type=\"datetime-local\"> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Button trigger modal -->\r\n");
      out.write("\t\t\t<!-- 이 문서내에 id가 exampleMoal인 것을 참조 -->\r\n");
      out.write("\t\t\t<!-- <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\">타사 카드 거래내역 연동</button> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal (1)-->\r\n");
      out.write("\t\t\t<!-- ID가 exampleModal 인 것을 참조 -->\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 이건 단순 이동이라 form 태그 필요없다. 수정 go -->\r\n");
      out.write("\t\t\t\t\t\t<form name=\"mform\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLabel\">인기 혜택별 순위</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- X표시를 눌러도 dismiss(닫기) 되도록 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Material unchecked -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p>인기 혜택별 순위</p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href = \"#\" data-dismiss=\"modal\">마트/쇼핑</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><a href = \"#\" data-dismiss=\"modal\">마트/쇼핑</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href = \"#\" data-dismiss=\"modal\">교통/주유</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href = \"#\" data-dismiss=\"modal\">레저/여행/항공</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href = \"#\" data-dismiss=\"modal\">반려동물</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href = \"#\" data-dismiss=\"modal\">보건/의료</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href = \"#\" data-dismiss=\"modal\">생활</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href = \"#\" data-dismiss=\"modal\">식음료</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href = \"#\" data-dismiss=\"modal\">통신</a></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div><a href = \"#\" data-dismiss=\"modal\">마트/쇼핑</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\">교통/주유</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\">레저/여행/항공</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\">반려동물</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\">보건/의료</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\">생활</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\">식음료</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\">통신</a></div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- a태그는 .click 안먹히네 그냥 아래 onclick 하자.\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a class = \"categoryA\" id = \"lifeA\" href = \"#\" data-dismiss=\"modal\" >생활</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a class = \"categoryA\" id = \"mart_shoppingA\" href = \"#\" data-dismiss=\"modal\" >마트/쇼핑</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a class = \"categoryA\" id = \"comm_transA\" href = \"#\" data-dismiss=\"modal\" >통신/교통</a></div> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a class = \"categoryA\" id = \"leisure_travle_flightA\" href = \"#\" data-dismiss=\"modal\" >레저/여행/항공</a></div>  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\" onclick =\"doChangeCondition('생활')\">생활</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\" onclick =\"doChangeCondition('마트/쇼핑')\">마트/쇼핑</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\" onclick =\"doChangeCondition('통신/교통')\">통신/교통</a></div> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div><a href = \"#\" data-dismiss=\"modal\" onclick =\"doChangeCondition('레저/여행/항공')\">레저/여행/항공</a></div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div><button data-dismiss=\"modal\">생활</button></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><button data-dismiss=\"modal\">마트/쇼핑</button></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><button data-dismiss=\"modal\">통신/교통</button></div> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div><button data-dismiss=\"modal\">레저/여행/항공</button></div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"modalBtn\">연동하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" id = \"modalBtn\">연동하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\tdismiss : 해산. 즉 버튼을 누르면 모달창을 닫음\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id = \"modalBtn\">연동하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\tdismiss : 해산. 즉 닫는다.\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div align=\"left\">\r\n");
      out.write("\t\t\t<!-- <div> -->\r\n");
      out.write("\t\t\t<!-- <div align=\"left\" style = \"border-left:1px solid lightgrey;\"> -->\r\n");
      out.write("\t\t\t<!-- <div align=\"left\" style = \"border:1px solid gold;\"> -->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<hr size = \"5\">\r\n");
      out.write("\t\t\t\t<ul id = \"ulList\" type = \"none\"> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Page level plugins -->\r\n");
      out.write("\t\t<script src=\"/hanacard-spring-mvc/resources/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t\t<script src=\"/hanacard-spring-mvc/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/hanacard-spring-mvc/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t\t<script src=\"/hanacard-spring-mvc/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t\t<script src=\"/hanacard-spring-mvc/resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Page level custom scripts -->\r\n");
      out.write("\t\t<!-- <script src=\"/hanacard-spring-mvc/resources/js/demo/chart-area-demo.js\"></script> -->\r\n");
      out.write("\t\t<!-- <script src=\"/hanacard-spring-mvc/resources/js/demo/chart-pie-demo.js\"></script> -->\r\n");
      out.write("\t\t<!-- <script src=\"/hanacard-spring-mvc/resources/js/demo/chart-bar-demo.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t//url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/recocard/' + year + '/' + month,\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart/benefitrank/life',\r\n");
      out.write("\t\t\ttype : 'get', \r\n");
      out.write("\t\t\t//async : false,\r\n");
      out.write("\t\t\tsuccess : function(data) { // data의 type : string --> json으로 바꾸자  ::  이용~ \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\talert('차트 alert 성공');\r\n");
      out.write("\t\t\t\talert('data: ' + data);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\talert('차트 ajax 실패')\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t*/\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- /.container-fluid -->\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- .site-wrap ends -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- loader -->\r\n");
      out.write("\t<div id=\"loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("\t\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("\t\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#51be78\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/aos.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery.fancybox.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery.sticky.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/jquery.mb.YTPlayer.min.js\"></script>\r\n");
      out.write("\t<script src=\"/hanacard-spring-mvc/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\"> -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script> -->\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/chart/benefitRank.jsp(411,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/chart/benefitRank.jsp(411,5) '${benefitSortList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${benefitSortList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/chart/benefitRank.jsp(411,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("top");
      // /WEB-INF/jsp/chart/benefitRank.jsp(411,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\t<div style = \"background-color: #E8F5FF; box-shadow: 20px 20px 20px grey;\">\r\n");
            out.write("\t\t\t\t\t\t\t<!-- <div style = \"background-color: #E8F5FF;\"> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t\t\t\t\t<span style = \"vertical-align: middle; font-weight : bold; font-size: 100px; color: black;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t\t\t\t\t<span>\r\n");
            out.write("\t\t\t\t\t\t\t\t<!-- <span style = \"middlevertical-align: middle\"> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t<!-- <span style = \"display: table-cell; vertical-align: middlevertical-align: middle\"> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t\t\t\t\t<span style =\"font-size: 30px; vertical-align: sub; color: black;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ top.cardName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t<br>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/chart/benefitRank.jsp(425,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fn:substring(top.cardName, 0, 1) == '#' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/hanacard-spring-mvc/resources/images/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ fn:substring(top.cardName, 1, fn:length(top.cardName)) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
          out.write(".png\" style = \"width : 132px; height : 84px;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/hanacard-spring-mvc/resources/images/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ top.cardName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(".png\" style = \"width : 132px; height : 84px;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
